### ISSUE TITLE
Convert Calendar to a function based widget

### ISSUE THREAD

**Issue by nicknisi** [dojo/widgets#1112]
**Enhancement** 

Convert the calendar widget to a functional widget.

- [x] Convert to functional widget using the appropriate middleware (#1189)
- [x] Convert hyperscript to TSX (#1189)
- [x] Ensure the properties align with the latest standards as seen in other converted widgets. (#1189)
- [x] Update tests (#1189)
- [ ] use theme.compose with a prefix to pass theme down to child widgets
- [ ] drop the aria bag in favour of specific properties where appropriate
- [ ] drop the controlled month / year / data props in favour on initialValue - the calendar should be able to manage these itself (Draft #1217)
- [ ] accept child renderers for month / weekday cell etc instead of properties (#1216)
- [ ] move child widgets (cell / datepicker etc) into the main Calendar file

**Comment by tomdye** [comment]
Additionally to the above we should:
- move child widgets (cell / datepicker etc) into the main Calendar file
- drop the aria bag in favour of specific properties where appropriate
- drop the controlled month / year / data props in favour on `initialValue` - the calendar should be able to manage these itself
- accept child renderers for month / weekday cell etc instead of properties

This issue should not simply be a conversion but a thought out rewrite

**Comment by tomdye** [comment]
@ericos adding you as an assignee on this task as you have more flex time available than @nicknisi , when you complete your other tasks please touch base with Nick to see where things are at before helping out.

**Comment by tomdye** [comment]
Closing this as the initial PR has been merged. Raising issues for remaining parts
