### ISSUE TITLE
Convert TabController to function based

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1171]
convert to function based and use TSX

- [x] convert hyperscript to tsx (#1188)
- [x] convert `TabController` and `TabButton` to functional widgets (#1188)
- [x] inline child widgets into the main `TabController` file (#1208)
- [x] remove controlled aspect of tab changing / closing (#1208)
- [x] use child renderer for children injecting the required properties to show / hide elements (#1208)
- [x] use theme.compose for child tabs
- [x] remove `index` param from tab button callbacks (#1208)

**Comment by mwistrand** [comment]
@tomdye Looking at how `<TabController>` is currently rendered, what is the benefit of using a child render like `(closedKeys: string[]): RenderResult` vs filtering out closed tabs from within `<TabController>`?
