### ISSUE TITLE
Checkbox Widget

### ISSUE THREAD

**Issue by pottedmeat** [dojo/widgets#622]
- mdc readme https://github.com/material-components/material-components-web/tree/master/packages/mdc-checkbox
- mdc docs https://material.io/design/components/selection-controls.html#checkboxes
- mdc demo https://material-components.github.io/material-components-web-catalog/#/component/checkbox

<img width="200" src="https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1nl-0NiKgfyT1d57Zzbni4-y6Mf-V4JXY%2Fwhen-to-use-checkboxes.png">

## Overview

This issue is concerned with implementing a material themed checkbox component.

## Changes to structure

* Material introduces `indeterminate` state as a separate flag but it seems like it should be a value that can be assigned to `checked` as they're mutually exclusive
* Remove `label` and require user to manual render a label widget and link it to the input via `for` and `id`.

## New properties

- `onKey(key: number, preventDefault: () => void)`: callback on `keyPress`

## Breaking changes

- will no longer offer `labelAfter` property
- will no longer offer `labelHidden` property
- will no longer offer `label` property
- will no longer offer `offLabel` property
- will no longer offer `onLabel` property
- will no longer call an `onChange` callback
- will no longer call `onKeyDown` / `onKeyPress`
- specific touch events have been removed
- `onBlur` / `onFocus` will no longer be passed the `value`
- Both switch and checkbox currently use the same codebase with a `mode` toggle. Switch will be moved to a separate widget.
	- will no longer offer `mode` property

## Tasks

- [x] Research dojo SVG support
- [x] Research parent/child behavior
- [ ] Document transition plan
- [ ] Restructure and update props
- [ ] Implement theme and update dojo theme

**Comment by tomdye** [comment]
This has been completed
