### ISSUE TITLE
Switch Widget

### ISSUE THREAD

**Issue by pottedmeat** [dojo/widgets#635]
- mdc readme https://github.com/material-components/material-components-web/tree/master/packages/mdc-switch
- mdc docs https://material.io/design/components/selection-controls.html#switches
- mdc demo https://material-components.github.io/material-components-web-catalog/#/component/switch

<img width="200" src="https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F18m9TuDx2ykggqxGIvNkPWIYllY-iqjBh%2Fselectioncontrols-switches-usage.png">

## Overview

This issue is concerned with implementing a material themed switch component.

## Changes to structure

* Remove `label` and require user to manual render a label widget and link it to the input via `for` and `id`.

## New properties

- `onKey(key: number, preventDefault: () => void)`: callback on `keyPress`

## Breaking changes

- will no longer offer `labelAfter` property
- will no longer offer `labelHidden` property
- will no longer offer `label` property
- will no longer offer `offLabel` property
- will no longer offer `onLabel` property
- will no longer call an `onChange` callback
- will no longer call `onKeyDown` / `onKeyPress`
- specific touch events have been removed
- `onBlur` / `onFocus` will no longer be passed the `value`
- Both switch and checkbox currently use the same codebase with a `mode` toggle. Switch is split out from the checkbox widget

## Tasks

- [ ] Document transition plan
- [ ] Restructure and update props
- [ ] Implement theme and update dojo theme

**Comment by tomdye** [comment]
@pottedmeat I think we'll still want to offer the `label` / `labelHidden` properties here as it's part of our `a11y` compliance.
Also I don't think this will need a `onKey` callback, it's a checkbox not a textinput capturing text entry.

**Comment by pottedmeat** [comment]
Can you talk more about what considerations we need to make for `a11y`? In terms of Material, they seem to prefer rendering labels separately in as many cases as possible.

With onKey, I was thinking it was there for detecting space vs. enter, etc. Do we have any guidelines for when its role is important?

**Comment by tomdye** [comment]
This has been completed
