### ISSUE TITLE
Widgets 7 Plan

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#780]
## Widgets 7 Plan

Epic for all the planned/desired enhancements to be released alongside Dojo v7.

**Note: Issue creation in progress across these**

### High Level Goals
- Widgets to be built and tested using the Dojo CLI exclusively
- Complete the Material theme
- Align and improve upon API of existing widgets
- Expansion of Widget library
- Create high-level layout / app widgets

### Use of CLI

Widgets currently use a fragmented dev toolchain. We should convert to using the dojo cli tooling consistently and ensure it has capability to build both `@dojo/widgets` and our user's third party component libraries.

- [x] [Use the dojo cli to test widgets](https://github.com/dojo/widgets/issues/787)
- [x] [Use the dojo cli to build and run widget examples](https://github.com/dojo/widgets/issues/747)

### Theme

The goal here is to create a material theme for our entire widget library. The structure for this was started in widgets 6 but not completed. The epic below links to the themes repo.

- [ ] [Material Theme](https://github.com/dojo/themes/issues/64)
- [x] [Upgrade build-theme to webpack 4](https://github.com/dojo/cli-build-theme/issues/20)

### Example / Test changes

Our existing functional tests are known to be flakey and to absorb large quantities of developer time both writing and fixing them. The framework itself is well tested across a range of browsers so there is little need to do this here also. We should ensure that adequate manual testing / usable examples are created when widgets are worked on.

- [x] [Drop existing functional tests](https://github.com/dojo/widgets/issues/781)
- [x] [Use codesandbox example approach to demonstrate widget functionality](https://github.com/dojo/widgets/issues/782)

### Existing widget improvements

This will be partly hangovers that did not get fully completed for dojo-6.0. This will make our existing widgets more compatible with the base / reusability direction we intend to take for dojo-7.0.

- [x] [Align `onValue` / `value` / `onKey` apis](https://github.com/dojo/widgets/issues/724)
- [x] [Align mouse / pointer events](https://github.com/dojo/widgets/issues/783)
- [x] [Change `invalid` -> `valid` properties](https://github.com/dojo/widgets/issues/786)
- [x] [Add `helperText` where appropriate](https://github.com/dojo/widgets/issues/677)
- [x] Select / Combobox property alignment / menu usage
- [ ] [Dialog improvements](https://github.com/dojo/widgets/issues/982)
- [ ] [~custom validator helpers~](https://github.com/dojo/widgets/issues/788)

### Split apart existing generic widgets

We have several overloaded widgets; checkbox, text-input, select etc. We should split them into smaller more focused widgets that work with a common base. The following list may not be extensive:

- [x] [email input](https://github.com/dojo/widgets/issues/789)
- [x] [number input](https://github.com/dojo/widgets/issues/790)
- [x] [telephone input](https://github.com/dojo/widgets/issues/791)
- [x] [constrained input](https://github.com/dojo/widgets/issues/793)
- [x] [password input](https://github.com/dojo/widgets/issues/792)
- [ ] [date input](https://github.com/dojo/widgets/issues/794)
- [ ] [type ahead](https://github.com/dojo/widgets/issues/795)
- [ ] [switch (take out of checkbox)](https://github.com/dojo/widgets/issues/796)
- [ ] [Add native select](https://github.com/dojo/widgets/issues/973)

### New Base Widgets

Creating new base widgets will give us a larger library to build more complex widgets on top of. This will help bulk out our offering and fill in the gaps required to build applications.

- [x] [Checkbox group](https://github.com/dojo/widgets/issues/797)
- [x] [Radio group](https://github.com/dojo/widgets/issues/798)
- [x] [Chip](https://github.com/dojo/widgets/issues/799)
- [~List~](https://github.com/dojo/widgets/issues/711)
- [~Item~](https://github.com/dojo/widgets/issues/712)
- [ ] Expansion panel (rework of title-pane?)
- [x] [Form (middleware?)](https://github.com/dojo/widgets/issues/800)
- [x] [Menu (to be used in dropdown / context / select / typeahead etc)](https://github.com/dojo/widgets/issues/801)
- [ ] [Paginated-menu](https://github.com/dojo/widgets/issues/1010)

### New Composite / Layout widgets

These widgets will use our existing base widgets to create highly re-usable and effecting application building blocks. These will be highly opinionated but fully themeable. 

- [ ] [Context menu](https://github.com/dojo/widgets/issues/938)
- [ ] Snackbar manager
- [ ] Sticky header
- [ ] [Login Widget](https://github.com/dojo/widgets/issues/1012])
- [ ] [Multi select typeahead (using chips and typeahead)](https://github.com/dojo/widgets/issues/1011)
- [ ] Confirmation dialog
- [ ] Stepped wizard
- [ ] 2 column layout
- [ ] 3 column layout
- [ ] list variants (tbd)
   - [ ] DND List

### Advice/guidelines for working on official widgets

- [ ] Use (new) official CLI toolchain
- [ ] Prefer function-based
- [ ] Prefer TSX
- [ ] Prefer simplicity and single, consistent ways of doing A Thing
- [ ] Use assertion template for testing
- [ ] Add examples in defined location & use these as 'integration' tests
- [ ] Document widget API in appropriate locations to allow auto-generation of portions of the widget docs on site
